#!/bin/sh

if [ -f /usr/lib/xmonad-contrib/package.env ]; then
	export GHC_ENVIRONMENT=/usr/lib/xmonad-contrib/package.env
else
	export GHC_ENVIRONMENT=/usr/lib/xmonad/package.env
fi

exec /usr/libexec/xmonad "$@"
